# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Eclipse OpenJ9 implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/eclipse-openj9"
  id = "paketo-buildpacks/eclipse-openj9"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for Eclipse OpenJ9"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/eclipse-openj9/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    build = true
    default = "11"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.0:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "OpenJ9 JDK"
    purl = "pkg:generic/ibmruntimes/semeru-jdk@8.0.332"
    sha256 = "82c8232a5cb420246457d65a5014602feb8b288079cdae896e22a2eb6e390b58"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u345-b01_openj9-0.33.0/ibm-semeru-open-jdk_x64_linux_8u345b01_openj9-0.33.0.tar.gz"
    version = "8.0.345"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.0:*:*:*:*:*:*:*"]
    id = "jre"
    name = "OpenJ9 JRE"
    purl = "pkg:generic/ibmruntimes/semeru-jre@8.0.332"
    sha256 = "0d4fe62716b9da2ccce324b5b46d57e8d47e5dfb5d128f87e16135ee9bc36cdc"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u345-b01_openj9-0.33.0/ibm-semeru-open-jre_x64_linux_8u345b01_openj9-0.33.0.tar.gz"
    version = "8.0.345"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.1:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "OpenJ9 JDK"
    purl = "pkg:generic/ibmruntimes/semeru-jdk@11.0.16"
    sha256 = "4eb9dc86bf92e144d7a2c8d6c2a6beac28c17b7348f2f0524e715548f52fd8f1"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.16.1%2B1_openj9-0.33.1/ibm-semeru-open-jdk_x64_linux_11.0.16.1_1_openj9-0.33.1.tar.gz"
    version = "11.0.16"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.1:*:*:*:*:*:*:*"]
    id = "jre"
    name = "OpenJ9 JRE"
    purl = "pkg:generic/ibmruntimes/semeru-jre@11.0.16"
    sha256 = "038a44d5c81f14bce6458040f7b4eec48535dcbbdc59e3c536d6adc3326b64c7"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.16.1%2B1_openj9-0.33.1/ibm-semeru-open-jre_x64_linux_11.0.16.1_1_openj9-0.33.1.tar.gz"
    version = "11.0.16"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.35.0:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "OpenJ9 JDK"
    purl = "pkg:generic/ibmruntimes/semeru-jdk@17.0.5"
    sha256 = "b46de9cd00af8a0223f4b50deb2627ab91fe515a69383a96fd2c12757cef24fe"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru17-binaries/releases/download/jdk-17.0.5%2B8_openj9-0.35.0/ibm-semeru-open-jdk_x64_linux_17.0.5_8_openj9-0.35.0.tar.gz"
    version = "17.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.1:*:*:*:*:*:*:*"]
    id = "jre"
    name = "OpenJ9 JRE"
    purl = "pkg:generic/ibmruntimes/semeru-jre@17.0.4"
    sha256 = "338ea5fe72f5a1a075c02953882a985dee437f0b60e432eacb02ba8ca15b3e0b"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru17-binaries/releases/download/jdk-17.0.4.1%2B1_openj9-0.33.1/ibm-semeru-open-jre_x64_linux_17.0.4.1_1_openj9-0.33.1.tar.gz"
    version = "17.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.0:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "OpenJ9 JDK"
    purl = "pkg:generic/ibmruntimes/semeru-jdk@18.0.2"
    sha256 = "48a7ea9b5043e5476b63d3b77b3bf01d71fd7fb53dd76db13865ce8bf8d4c09f"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru18-binaries/releases/download/jdk-18.0.2%2B9_openj9-0.33.0/ibm-semeru-open-jdk_x64_linux_18.0.2_9_openj9-0.33.0.tar.gz"
    version = "18.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:eclipse:openj9:0.33.0:*:*:*:*:*:*:*"]
    id = "jre"
    name = "OpenJ9 JRE"
    purl = "pkg:generic/ibmruntimes/semeru-jre@18.0.2"
    sha256 = "31f9c08f3b742e4055efa6e4bbf8d9e5be02c775c8fe2c68dd4a460a8ed52c28"
    stacks = ["*"]
    uri = "https://github.com/ibmruntimes/semeru18-binaries/releases/download/jdk-18.0.2%2B9_openj9-0.33.0/ibm-semeru-open-jre_x64_linux_18.0.2_9_openj9-0.33.0.tar.gz"
    version = "18.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
      uri = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[stacks]]
  id = "*"
